### ISSUE TITLE
bitmanip opcode encoding table: FSRI overlap SBEXTI, GORCI, GREVI, RORI, SROI, SRAI, SRLI?

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-bitmanip#61]
Hi,
in the opcode encodings table, FSRI shows that bit 26 needs to be 1.  Can we add to the table that SBEXTI, GORCI, GREVI, RORI, SROI, SRAI, SRLI bit 26 needs to be 0?  Otherwise it looks like there is overlap in the encodings.  I see the text above the table mentions op[26]=1 selects funnel shifts, but it might be helpful to show in the table as well.

Thanks,
Dan

**Comment by cliffordwolf** [comment]
Quoting the text on page 41:

> On RV128 op[26] contains the MSB of the immediate for the shift instructions. Therefore there is no FSRI instruction on RV128.  (But there is FSRIW/FSRID.)

So we cannot say that "SBEXTI, GORCI, GREVI, RORI, SROI, SRAI, SRLI bit 26 needs to be 0" generally because that might not be true on RV128. (We don't know the details of the RV128 spec yet.) On RV64 and RV32 it's always zero because on those architectures the imm field is one or two bits shorter. Again, quoting the text on page 41:

> Just like int he RISC-V integer base ISA, the shift-immediate instructions have a 5 bit immediate on RV32, and a 6 bit immediate on RV64, and we reserve encoding space for a 7 bit immediate for RV128.
